FROM alpine:latest

RUN apk update
RUN apk add openssh \
                gcc \
                make \
                valgrind \ 
                check-dev \
                musl-dev \
                clang-dev \
                pcre-dev \
                bash \
                subunit-dev \
                build-base